# 多層感知器實作

## 載入套件

In [24]:
import tensorflow as tf
import input_data

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


## 訓練資料

In [25]:
batch_xs, batch_ys = mnist.train.next_batch(5)

## 建立Computational Graph

In [26]:
x_ = tf.placeholder(tf.float32, [None, 784], name="x_")
y_ = tf.placeholder(tf.float32, [None, 10], name="y_")

W1 = tf.Variable(tf.truncated_normal([784,200], stddev=0.1), name="W1")
b1 = tf.Variable(tf.zeros([200]), name="b1")
h1 = tf.nn.sigmoid(tf.matmul(x_, W1) + b1)
W2 = tf.Variable(tf.truncated_normal([200,10], stddev=0.1), name="W2")
b2 = tf.Variable(tf.zeros([10]), name="b2")
y = tf.nn.softmax(tf.matmul(h1, W2) + b2)

cross_entropy = -tf.reduce_sum(y_ * tf.log(y))

optimizer = tf.train.GradientDescentOptimizer(0.01)
trainer = optimizer.minimize(cross_entropy)

init = tf.initialize_all_variables()


## Session

In [27]:
sess = tf.Session()
sess.run(init)

## W1

In [28]:
sess.run(W1)
import json
import numpy as np
f = open("w1.json","w")
f.write(json.dumps(sess.run(W1).reshape([784*200]).tolist()))
f.close()

In [29]:
sess.run(W1).shape

(784, 200)

## b1

In [30]:
sess.run(b1)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [31]:
sess.run(b1).shape

(200,)

## h1

In [32]:
result_h1 = sess.run(h1,feed_dict={x_: batch_xs})
result_h1

array([[ 0.12379336,  0.23834296,  0.23781149,  0.78446555,  0.4394207 ,
         0.31980702,  0.6118297 ,  0.49437079,  0.2826716 ,  0.4188292 ,
         0.6771704 ,  0.30778906,  0.63065279,  0.38982818,  0.8315258 ,
         0.30549753,  0.50432312,  0.52076334,  0.29190221,  0.56478041,
         0.43487674,  0.35891706,  0.69239116,  0.52397764,  0.30501488,
         0.55985934,  0.33671442,  0.33044469,  0.88144177,  0.6144079 ,
         0.37240666,  0.79779011,  0.44908875,  0.65616482,  0.69096589,
         0.2703501 ,  0.50154966,  0.16868594,  0.62515587,  0.55745995,
         0.23215693,  0.38000208,  0.37015817,  0.43198666,  0.50486076,
         0.6069243 ,  0.73426896,  0.39424309,  0.53940469,  0.30204761,
         0.40286767,  0.41102251,  0.6608367 ,  0.50625062,  0.78610128,
         0.48271579,  0.35434377,  0.76682448,  0.7380594 ,  0.73283899,
         0.4446891 ,  0.4631632 ,  0.90823448,  0.70809484,  0.53354007,
         0.88829702,  0.46612349,  0.48421139,  0.5

In [33]:
result_h1.shape

(5, 200)

## W2

In [34]:
sess.run(W2)

array([[ 0.09773866,  0.1660856 ,  0.01633508, ..., -0.03397912,
        -0.10511833,  0.07120276],
       [ 0.02577358, -0.06520128,  0.1034446 , ...,  0.12558162,
        -0.05753119, -0.05540506],
       [-0.0460937 , -0.13260718, -0.10929547, ..., -0.13128507,
        -0.09371874, -0.07618532],
       ..., 
       [ 0.11473997, -0.13836408, -0.190373  , ...,  0.00255204,
        -0.06542861,  0.11895118],
       [ 0.13804422, -0.03782111, -0.0134181 , ..., -0.01465242,
        -0.02481445, -0.13727354],
       [-0.0142282 , -0.00874954,  0.08670824, ..., -0.06446308,
         0.0222198 , -0.05926232]], dtype=float32)

In [35]:
sess.run(W2).shape

(200, 10)

## b2

In [36]:
sess.run(b2)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [37]:
sess.run(b2).shape

(10,)

## y

In [38]:
result_y = sess.run(y,feed_dict={x_: batch_xs})
result_y

array([[ 0.12666777,  0.06390521,  0.02692422,  0.11513191,  0.20151401,
         0.1174376 ,  0.14449129,  0.03476105,  0.10786197,  0.06130497],
       [ 0.15683289,  0.05593039,  0.03690217,  0.0626167 ,  0.22693284,
         0.1650428 ,  0.14843306,  0.02292238,  0.08229436,  0.04209238],
       [ 0.15162654,  0.05951981,  0.04158129,  0.07322458,  0.15315843,
         0.17833304,  0.14711526,  0.02400655,  0.11675857,  0.05467593],
       [ 0.09934454,  0.07409507,  0.02801087,  0.09103332,  0.21604496,
         0.21881865,  0.11597573,  0.02420439,  0.07851373,  0.05395876],
       [ 0.08367379,  0.07389692,  0.03419016,  0.0657652 ,  0.21631595,
         0.21504669,  0.15252425,  0.02668291,  0.08051154,  0.05139265]], dtype=float32)

In [39]:
result_y.shape

(5, 10)

## Cross Entropy

In [40]:
result_cross_entropy = sess.run(cross_entropy  ,feed_dict={x_: batch_xs, y_:batch_ys})
result_cross_entropy

12.765722

## 建立成效評估用的Computational Graph

In [41]:
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

## 驗證資料

In [42]:
mnist.validation.images

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [43]:
mnist.validation.images.shape

(5000, 784)

mnist.validation.labels

In [44]:
mnist.validation.labels.shape

(5000, 10)

## Saver

In [45]:
saver = tf.train.Saver()

## 訓練

In [46]:
patience = 50
best_accurarcy = 0
i = 0
while True:
    i += 1
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(trainer,  feed_dict={x_: batch_xs, y_: batch_ys})
    if i%20 == 0:
        train_accurarcy = sess.run(accuracy, feed_dict={x_: batch_xs, y_: batch_ys})
        valid_accurarcy = sess.run(accuracy, feed_dict={x_: mnist.validation.images, y_: mnist.validation.labels})
        print "%s, train: %s, valid: %s" %(i, train_accurarcy, valid_accurarcy)
        if valid_accurarcy > best_accurarcy:
            patience = 50
            best_accurarcy = valid_accurarcy
            print "save model"
            saver.save(sess, "model_multilayer_perceptron.ckpt")
        else:
            patience -= 1
            if patience == 0:
                print "early stop"
                break 

20, train: 0.81, valid: 0.7604
save model
40, train: 0.82, valid: 0.8176
save model
60, train: 0.9, valid: 0.8454
save model
80, train: 0.83, valid: 0.8608
save model
100, train: 0.95, valid: 0.8892
save model
120, train: 0.88, valid: 0.8916
save model
140, train: 0.95, valid: 0.8936
save model
160, train: 0.89, valid: 0.8984
save model
180, train: 0.97, valid: 0.905
save model
200, train: 0.91, valid: 0.893
220, train: 0.97, valid: 0.9086
save model
240, train: 0.93, valid: 0.9092
save model
260, train: 0.96, valid: 0.9064
280, train: 0.95, valid: 0.9172
save model
300, train: 0.92, valid: 0.9194
save model
320, train: 0.96, valid: 0.9098
340, train: 0.98, valid: 0.9196
save model
360, train: 0.94, valid: 0.9242
save model
380, train: 0.93, valid: 0.9188
400, train: 0.95, valid: 0.9208
420, train: 0.96, valid: 0.925
save model
440, train: 0.87, valid: 0.9036
460, train: 0.99, valid: 0.9246
480, train: 0.91, valid: 0.9226
500, train: 0.94, valid: 0.925
520, train: 0.96, valid: 0.9334
s

In [48]:
saver.restore(sess, "model_multilayer_perceptron.ckpt")
valid_accurarcy = sess.run(accuracy, feed_dict={x_: mnist.validation.images, y_: mnist.validation.labels})
test_accurarcy = sess.run(accuracy, feed_dict={x_: mnist.test.images, y_: mnist.test.labels})
print "valid:%s, test:%s"%(valid_accurarcy,test_accurarcy)
# valid:0.98 ,test:0.9779

valid:0.9824, test:0.9793
